module SkelJ where

-- Haskell module generated by the BNF converter

import AbsJ
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transPrg :: Prg -> Result
transPrg x = case x of
  Program exps -> failure x
transExp :: Exp -> Result
transExp x = case x of
  EBipush integer -> failure x
  EAdd -> failure x
  ESub -> failure x
  EDiv -> failure x
  EMul -> failure x
  EPop -> failure x
  EJump integer -> failure x
  EJlt integer1 integer2 -> failure x

