package Calc.Absyn; // Java Package generated by the BNF Converter.

public class ESqrt  extends Exp {
  public final Exp exp_;
  public ESqrt(Exp p1) { exp_ = p1; }

  public <R,A> R accept(Calc.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Calc.Absyn.ESqrt) {
      Calc.Absyn.ESqrt x = (Calc.Absyn.ESqrt)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
