

module AbsGrammar where

-- Haskell module generated by the BNF converter




newtype Letter = Letter String deriving (Eq, Ord, Show, Read)
data Exp
    = ESymbol Letter
    | ESequence Exp Exp
    | EUnion Exp Exp
    | EClosure Exp
  deriving (Eq, Ord, Show, Read)

